In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [53]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

### Read data

In [58]:
df1 = pd.read_csv('./data/LoanStats_securev1_2017Q1.csv', skiprows=[0])
df2 = pd.read_csv('./data/LoanStats_securev1_2017Q2.csv', skiprows=[0])
df3 = pd.read_csv('./data/LoanStats_securev1_2017Q3.csv', skiprows=[0])
df4 = pd.read_csv('./data/LoanStats3c_securev1_2014.csv', skiprows=[0])
df5 = pd.read_csv('./data/LoanStats3d_securev1_2015.csv', skiprows=[0])

/Users/sabber/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0,118,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/sabber/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/sabber/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0,129,130,131,134,135,136,139,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/sabber/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0,19,129,130,131,134,135,136,139) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Users/sabber/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0,19,59) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [60]:
df = pd.concat([df1, df2, df3, df4, df5])

### Get domain knowledge

In [61]:
df.shape

(981665, 151)

In [74]:
print(list(df.columns))

['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'annual_inc', 'verification_status', 'issue_d', 'loan_status', 'pymnt_plan', 'url', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line', 'fico_range_low', 'fico_range_high', 'inq_last_6mths', 'mths_since_last_delinq', 'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc', 'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee', 'recoveries', 'collection_recovery_fee', 'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d', 'last_fico_range_high', 'last_fico_range_low', 'collections_12_mths_ex_med', 'mths_since_last_major_derog', 'policy_code', 'application_type', 'annual_inc_joint', 'dti_joint', 'verification_status_joint', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m', 'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util', 'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_bc_dlq', 'mths_since_recent_inq', 'mths_since_recent_revol_delinq', 'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit', 'revol_bal_joint', 'sec_app_fico_range_low', 'sec_app_fico_range_high', 'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths', 'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util', 'sec_app_open_act_il', 'sec_app_num_rev_accts', 'sec_app_chargeoff_within_12_mths', 'sec_app_collections_12_mths_ex_med', 'sec_app_mths_since_last_major_derog', 'hardship_flag', 'hardship_type', 'hardship_reason', 'hardship_status', 'deferral_term', 'hardship_amount', 'hardship_start_date', 'hardship_end_date', 'payment_plan_start_date', 'hardship_length', 'hardship_dpd', 'hardship_loan_status', 'orig_projected_additional_accrued_interest', 'hardship_payoff_balance_amount', 'hardship_last_payment_amount', 'disbursement_method', 'debt_settlement_flag', 'debt_settlement_flag_date', 'settlement_status', 'settlement_date', 'settlement_amount', 'settlement_percentage', 'settlement_term']

In [62]:
df.head(5)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,104046719,NaN,14000.0,14000.0,14000.0,36 months,15.99%,492.13,C,C5,Project Leader,10+ years,MORTGAGE,82000.0,Source Verified,Mar-2017,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,credit_card,Credit card refinancing,672xx,KS,31.07,0.0,May-1996,725.0,729.0,0.0,NaN,NaN,18.0,0.0,69578.0,63.2%,31.0,w,11438.26,11438.26,3912.17,3912.17,2561.74,1350.43,0.0,0.0,0.0,Dec-2017,492.13,Jan-2018,Dec-2017,714.0,710.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,202617.0,0.0,3.0,0.0,1.0,22.0,34430.0,57.0,0.0,2.0,13686.0,61.0,110037.0,0.0,9.0,0.0,3.0,11257.0,29762.0,63.4,0.0,0.0,140.0,250.0,13.0,13.0,6.0,13.0,NaN,13.0,NaN,0.0,7.0,9.0,8.0,13.0,4.0,14.0,21.0,9.0,18.0,0.0,0.0,0.0,0.0,100.0,25.0,0.0,0.0,286204.0,104008.0,81400.0,60167.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,104048967,NaN,5000.0,5000.0,5000.0,36 months,25.49%,200.10,E,E4,Pilot,10+ years,MORTGAGE,215000.0,Source Verified,Mar-2017,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,067xx,CT,6.06,0.0,Jan-2004,765.0,769.0,4.0,NaN,NaN,11.0,0.0,8678.0,18.8%,16.0,f,4190.59,4190.59,1586.64,1586.64,809.41,777.23,0.0,0.0,0.0,Dec-2017,200.10,Jan-2018,Dec-2017,779.0,775.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,44754.0,1.0,3.0,2.0,4.0,7.0,35832.0,68.0,2.0,2.0,8659.0,27.0,46200.0,2.0,0.0,6.0,6.0,4069.0,37522.0,18.8,0.0,0.0,83.0,87.0,5.0,5.0,0.0,5.0,NaN,0.0,NaN,0.0,2.0,2.0,7.0,8.0,7.0,7.0,8.0,2.0,11.0,0.0,0.0,0.0,4.0,100.0,0.0,0.0,0.0,100763.0,44754.0,46200.0,49814.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,104028593,NaN,4600.0,4600.0,4600.0,36 months,11.39%,151.45,B,B3,cable technician,4 years,RENT,44470.0,Not Verified,Mar-2017,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,credit_card,Credit card refinancing,066xx,CT,13.43,0.0,Dec-2003,770.0,774.0,1.0,NaN,NaN,7.0,0.0,5400.0,19.1%,11.0,w,3708.50,3708.50,1205.78,1205.78,891.50,314.28,0.0,0.0,0.0,Dec-2017,151.45,Jan-2018,Dec-2017,769.0,765.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,9625.0,1.0,1.0,0.0,1.0,22.0,4225.0,36.0,2.0,4.0,4670.0,24.0,28300.0,0.0,0.0,1.0,5.0,1375.0,9610.0,33.7,0.0,0.0,77.0,159.0,1.0,1.0,0.0,7.0,NaN,1.0,NaN,0.0,2.0,3.0,3.0,4.0,2.0,6.0,9.0,3.0,7.0,0.0,0.0,0.0,2.0,100.0,0.0,0.0,0.0,40000.0,9625.0,14500.0,11700.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,104046702,NaN,14000.0,14000.0,14000.0,60 months,12.74%,316.69,C,C1,Specialty Sales,4 years,OWN,40000.0,Not Verified,Mar-2017,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,credit_card,Credit card refinancing,926xx,CA,17.48,0.0,Feb-1974,715.0,719.0,0.0,NaN,NaN,10.0,0.0,25787.0,46.2%,23.0,w,12604.51,12604.51,2585.32,2585.32,1395.49,1189.83,0.0,0.0,0.0,Dec-2017,316.69,Jan-2018,Dec-2017,714.0,710.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,25787.0,2.0,0.0,0.0,0.0,129.0,0.0,NaN,5.0,7.0,8549.0,46.0,55800.0,0.0,3.0,0.0,7.0,2579.0,27153.0,48.3,0.0,0.0,129.0,517.0,1.0,1.0,1.0,2.0,NaN,23.0,NaN,0.0,7.0,9.0,8.0,13.0,1.0,10.0,21.0,9.0,10.0,0.0,0.0,0.0,5.0,100.0,37.5,0.0,0.0,55800.0,25787.0,52500.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,104280113,NaN,15000.0,15000.0,15000.0,36 months,5.32%,451.73,A,A1,Executive Account Manager,10+ years,MORTGAGE,182000.0,Not Verified,Mar-2017,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,751xx,TX,9.35,0.0,Nov-1974,740.0,744.0,0.0,NaN,NaN,13.0,0.0,34623.0,33.7%,32.0,w,11869.91,11869.91,3604.97,3604.97,3130.09,474.88,0.0,0.0,0.0,Dec-2017,451.73,Jan-2018,Dec-2017,734.0,730.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,233521.0,0.0,1.0,0.0,1.0,24.0,2667.0,59.0,2.0,2.0,12503.0,42.0,102600.0,1.0,6.0,0.0,4.0,17963.0,55203.0,26.0,0.0,0.0,92.0,508.0,8.0,8.0,5.0,8.0,NaN,17.0,NaN,0.0,3.0,6.0,7.0,11.0,9.0,10.0,16.0,6.0,13.0,0.0,0.0,0.0,2.0,100.0,0.0,0.0,0.0,325464.0,50766.0,74600.0,4508.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
df.dtypes.sort_values().to_frame('feature_type').groupby(by = 'feature_type').size().to_frame('count').reset_index()

  feature_type  count
0      float64    111
1       object     40

In [75]:
df_dtypes = pd.merge(df.isnull().sum(axis = 0).sort_values().to_frame('missing_value').reset_index(),
         df.dtypes.to_frame('feature_type').reset_index(),
         on = 'index',
         how = 'inner')

In [76]:
df_dtypes.sort_values(['missing_value', 'feature_type'])

                                          index  missing_value feature_type
0                                            id              0       object
1                                   tot_cur_bal             10      float64
2                                  tot_coll_amt             10      float64
3                                acc_now_delinq             10      float64
4                               tot_hi_cred_lim             10      float64
5                             total_bal_ex_mort             10      float64
6                                total_bc_limit             10      float64
8                                   policy_code             10      float64
9                    total_il_high_credit_limit             10      float64
10                   collections_12_mths_ex_med             10      float64
11                          last_fico_range_low             10      float64
12                         last_fico_range_high             10      float64
13                              last_pymnt_amnt             10      float64
14                               num_actv_bc_tl             10      float64
15                      collection_recovery_fee             10      float64
16                                   recoveries             10      float64
17                           total_rec_late_fee             10      float64
18                                    tax_liens             10      float64
19                                total_rec_int             10      float64
20                         pub_rec_bankruptcies             10      float64
21                           num_tl_op_past_12m             10      float64
22                        num_accts_ever_120_pd             10      float64
23                                  num_bc_sats             10      float64
24                                     mort_acc             10      float64
25                               mo_sin_rcnt_tl             10      float64
26                        mo_sin_rcnt_rev_tl_op             10      float64
27                         mo_sin_old_rev_tl_op             10      float64
28                                  delinq_amnt             10      float64
29                     chargeoff_within_12_mths             10      float64
30                         acc_open_past_24mths             10      float64
31                                    num_bc_tl             10      float64
32                                    num_il_tl             10      float64
33                                num_op_rev_tl             10      float64
34                             total_rev_hi_lim             10      float64
35                          num_rev_tl_bal_gt_0             10      float64
36                                     num_sats             10      float64
37                                 num_tl_30dpd             10      float64
38                           num_tl_90g_dpd_24m             10      float64
39                               pct_tl_nvr_dlq             10      float64
40                              total_rec_prncp             10      float64
41                              num_actv_rev_tl             10      float64
42                                  total_pymnt             10      float64
44                              total_pymnt_inv             10      float64
48                                   annual_inc             10      float64
52                                  installment             10      float64
55                              funded_amnt_inv             10      float64
56                                  funded_amnt             10      float64
57                                    loan_amnt             10      float64
62                                      pub_rec             10      float64
63                                out_prncp_inv             10      float64
64                                    out_prncp             10      float64
66                                  delinq_2yrs             10      float64
68                               fico_range_low             10      float64
69                              fico_range_high             10      float64
70                                    total_acc             10      float64
71                               inq_last_6mths             10      float64
72                                    revol_bal             10      float64
75                                     open_acc             10      float64
7                              application_type             10       object
43                                          url             10       object
45                                  loan_status             10       object
46                                      issue_d             10       object
47                          verification_status             10       object
49                               home_ownership             10       object
50                          disbursement_method             10       object
51                                    sub_grade             10       object
53                                     int_rate             10       object
54                                         term             10       object
58                         debt_settlement_flag             10       object
59                                        grade             10       object
60                                      purpose             10       object
61                                   pymnt_plan             10       object
65                          initial_list_status             10       object
67                             earliest_cr_line             10       object
73                                   addr_state             10       object
74                                hardship_flag             10       object
77                                num_rev_accts             11      float64
76                                     zip_code             11       object
78                                  avg_cur_bal             23      float64
79                           last_credit_pull_d             50       object
80                                        title            142       object
81                                          dti            304      float64
82                                   revol_util            550       object
83                                 last_pymnt_d            878       object
84                         mths_since_recent_bc           9718      float64
85                               bc_open_to_buy          10282      float64
86                             percent_bc_gt_75          10677      float64
87                                      bc_util          10862      float64
88                           mo_sin_old_il_acct          28220      float64
89                             num_tl_120dpd_2m          42519      float64
90                                   emp_length          57995       object
91                                    emp_title          59595       object
92                        mths_since_recent_inq         103454      float64
93                                 next_pymnt_d         457738       object
94                       mths_since_last_delinq         477730      float64
95               mths_since_recent_revol_delinq         631372      float64
96                                       inq_fi         635362      float64
97                                 inq_last_12m         635362      float64
98                                  open_acc_6m         635362      float64
99                                  open_act_il         635362      float64
100                                 open_il_24m         635362      float64
101                                total_bal_il         635362      float64
102                                 open_rv_12m         635362      float64
103                                 open_il_12m         635362      float64
104                                  max_bal_bc         635362      float64
105                                 total_cu_tl         635362      float64
106                                 open_rv_24m         635362      float64
107                                    all_util         635392      float64
108                          mths_since_rcnt_il         644709      float64
109                                     il_util         681303      float64
110                 mths_since_last_major_derog         702961      float64
111                    mths_since_recent_bc_dlq         732439      float64
112                      mths_since_last_record         807460      float64
114                            annual_inc_joint         955940      float64
113                   verification_status_joint         955940       object
115                                   dti_joint         955942      float64
116          sec_app_collections_12_mths_ex_med         959840      float64
117            sec_app_chargeoff_within_12_mths         959840      float64
118                       sec_app_num_rev_accts         959840      float64
119                            sec_app_open_acc         959840      float64
120                         sec_app_open_act_il         959840      float64
121                      sec_app_inq_last_6mths         959840      float64
123                     sec_app_fico_range_high         959840      float64
124                      sec_app_fico_range_low         959840      float64
125                             revol_bal_joint         959840      float64
126                            sec_app_mort_acc         959840      float64
122                    sec_app_earliest_cr_line         959840       object
127                          sec_app_revol_util         960128      float64
128                                        desc         966341       object
129                           settlement_amount         973035      float64
133                             settlement_term         973035      float64
134                       settlement_percentage         973035      float64
130                             settlement_date         973035       object
131                           settlement_status         973035       object
132                   debt_settlement_flag_date         973035       object
135         sec_app_mths_since_last_major_derog         974124      float64
140                             hardship_amount         978661      float64
141                hardship_last_payment_amount         978661      float64
143                                hardship_dpd         978661      float64
144                             hardship_length         978661      float64
146                               deferral_term         978661      float64
147              hardship_payoff_balance_amount         978661      float64
136                         hardship_start_date         978661       object
137                               hardship_type         978661       object
138                             hardship_reason         978661       object
139                             hardship_status         978661       object
142                        hardship_loan_status         978661       object
145                     payment_plan_start_date         978661       object
148                           hardship_end_date         978661       object
149  orig_projected_additional_accrued_interest         979086      float64
150                                   member_id         981665      float64

### Feature selections and clean